"""
core/report.py – HTML/PDF report generation with embedded Plotly charts and auto summaries.
"""
from __future__ import annotations

import base64
import io
from datetime import datetime
from typing import Any

import pandas as pd
import plotly.graph_objects as go


# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #222; background: #fafafa; }}
  h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 8px; }}
  h2 {{ color: #34495e; border-left: 4px solid #3498db; padding-left: 10px; margin-top: 32px; }}
  h3 {{ color: #555; }}
  .section {{ background: white; border-radius: 8px; padding: 20px; margin-bottom: 24px;
              box-shadow: 0 1px 4px rgba(0,0,0,.08); }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 10px; font-size: 13px; }}
  th {{ background: #3498db; color: white; padding: 8px 12px; text-align: left; }}
  td {{ padding: 6px 12px; border-bottom: 1px solid #eee; }}
  tr:nth-child(even) {{ background: #f8f9fa; }}
  .kv {{ display: flex; flex-wrap: wrap; gap: 16px; margin-top: 12px; }}
  .kv-item {{ background: #ecf0f1; border-radius: 6px; padding: 10px 16px; min-width: 120px; }}
  .kv-label {{ font-size: 11px; color: #888; text-transform: uppercase; }}
  .kv-value {{ font-size: 18px; font-weight: bold; color: #2c3e50; }}
  .interpretation {{ background: #eaf4fb; border-left: 3px solid #3498db;
                     padding: 10px 14px; border-radius: 4px; margin-top: 10px; font-size: 13px; }}
  .chart-container {{ margin: 16px 0; }}
  .footer {{ color: #aaa; font-size: 11px; text-align: center; margin-top: 40px; }}
  .tag {{ display: inline-block; background: #d5e8f9; color: #1a5f8a; border-radius: 12px;
          padding: 2px 10px; font-size: 11px; margin: 2px; }}
</style>
</head>
<body>
<h1>{title}</h1>
<p style="color:#888">Generated: {timestamp} &nbsp;|&nbsp; Dataset: {dataset_name} &nbsp;|&nbsp; Rows: {n_rows}</p>
{body}
<div class="footer">Generated by KIBAD · {timestamp}</div>
</body>
</html>
"""

_SECTION_TEMPLATE = """
<div class="section">
  <h2>{heading}</h2>
  {content}
</div>
"""


# ---------------------------------------------------------------------------
# Helper: fig → inline SVG / PNG base64
# ---------------------------------------------------------------------------

def _fig_to_html_img(fig: go.Figure, width: int = 900, height: int = 400) -> str:
    """Convert a Plotly figure to an inline base64 PNG img tag."""
    try:
        img_bytes = fig.to_image(format="png", width=width, height=height, scale=1.5)
        b64 = base64.b64encode(img_bytes).decode()
        return f'<div class="chart-container"><img src="data:image/png;base64,{b64}" style="max-width:100%;border-radius:6px"/></div>'
    except Exception:
        # Fallback to HTML div (requires kaleido; if missing, embed as HTML snippet)
        return f'<div class="chart-container"><em>[Chart could not be embedded – install kaleido]</em></div>'


def _fig_to_html_div(fig: go.Figure) -> str:
    """Convert a Plotly figure to an inline HTML div (no kaleido needed)."""
    try:
        return fig.to_html(full_html=False, include_plotlyjs="cdn")
    except Exception:
        return "<em>[Chart unavailable]</em>"


def _df_to_html_table(df: pd.DataFrame, max_rows: int = 50) -> str:
    """Convert a DataFrame to an HTML table string."""
    if df is None or df.empty:
        return "<em>No data.</em>"
    subset = df.head(max_rows)
    rows = "".join(
        f"<tr>{''.join(f'<td>{v}</td>' for v in row)}</tr>"
        for row in subset.values
    )
    headers = "".join(f"<th>{c}</th>" for c in subset.columns)
    return f"<table><thead><tr>{headers}</tr></thead><tbody>{rows}</tbody></table>"


def _kv_cards(items: dict[str, Any]) -> str:
    """Render a set of key-value metric cards."""
    cards = "".join(
        f'<div class="kv-item"><div class="kv-label">{k}</div><div class="kv-value">{v}</div></div>'
        for k, v in items.items()
    )
    return f'<div class="kv">{cards}</div>'


def _interp_box(text: str) -> str:
    return f'<div class="interpretation">{text}</div>'


# ---------------------------------------------------------------------------
# Report builder
# ---------------------------------------------------------------------------

class ReportBuilder:
    """Incrementally build a KIBAD HTML report.

    Usage::

        rb = ReportBuilder(title="Q1 Sales Analysis", dataset_name="sales.csv", n_rows=500)
        rb.add_section("Data Profile", content_html="<p>...</p>")
        rb.add_figure("Time Series", fig)
        html = rb.render()
    """

    def __init__(
        self,
        title: str = "KIBAD Analysis Report",
        dataset_name: str = "",
        n_rows: int = 0,
    ) -> None:
        self.title = title
        self.dataset_name = dataset_name
        self.n_rows = n_rows
        self._sections: list[str] = []

    def add_section(self, heading: str, content_html: str) -> "ReportBuilder":
        """Add a free-form HTML section.

        Parameters
        ----------
        heading:
            Section heading.
        content_html:
            Raw HTML content.

        Returns
        -------
        ReportBuilder
        """
        self._sections.append(
            _SECTION_TEMPLATE.format(heading=heading, content=content_html)
        )
        return self

    def add_kv_metrics(self, heading: str, metrics: dict[str, Any]) -> "ReportBuilder":
        """Add a key-value metrics card section.

        Parameters
        ----------
        heading:
            Section heading.
        metrics:
            Dict of label → value.

        Returns
        -------
        ReportBuilder
        """
        return self.add_section(heading, _kv_cards(metrics))

    def add_table(
        self,
        heading: str,
        df: pd.DataFrame,
        interpretation: str = "",
        max_rows: int = 50,
    ) -> "ReportBuilder":
        """Add a DataFrame as an HTML table.

        Parameters
        ----------
        heading:
            Section heading.
        df:
            DataFrame to render.
        interpretation:
            Optional business interpretation text.
        max_rows:
            Maximum rows to include.

        Returns
        -------
        ReportBuilder
        """
        content = _df_to_html_table(df, max_rows=max_rows)
        if interpretation:
            content += _interp_box(interpretation)
        return self.add_section(heading, content)

    def add_figure(
        self,
        heading: str,
        fig: go.Figure,
        interpretation: str = "",
        inline_html: bool = True,
    ) -> "ReportBuilder":
        """Add a Plotly figure.

        Parameters
        ----------
        heading:
            Section heading.
        fig:
            Plotly Figure object.
        interpretation:
            Optional text below the chart.
        inline_html:
            If True, embed as interactive HTML; if False, try PNG (requires kaleido).

        Returns
        -------
        ReportBuilder
        """
        if inline_html:
            chart_html = _fig_to_html_div(fig)
        else:
            chart_html = _fig_to_html_img(fig)
        content = chart_html
        if interpretation:
            content += _interp_box(interpretation)
        return self.add_section(heading, content)

    def add_interpretation(self, heading: str, text: str) -> "ReportBuilder":
        """Add a plain interpretation/text block.

        Parameters
        ----------
        heading:
            Section heading.
        text:
            Narrative text.

        Returns
        -------
        ReportBuilder
        """
        return self.add_section(heading, _interp_box(text))

    def render(self) -> str:
        """Render the full HTML report as a string.

        Returns
        -------
        str
            Complete HTML document.
        """
        body = "\n".join(self._sections)
        return _HTML_TEMPLATE.format(
            title=self.title,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
            dataset_name=self.dataset_name or "—",
            n_rows=self.n_rows,
            body=body,
        )

    def to_bytes(self) -> bytes:
        """Return rendered HTML as UTF-8 bytes.

        Returns
        -------
        bytes
        """
        return self.render().encode("utf-8")


# ---------------------------------------------------------------------------
# Auto business summary generator
# ---------------------------------------------------------------------------

def generate_business_summary(
    df: pd.DataFrame,
    date_col: str,
    target_col: str,
    forecast_result: Any | None = None,
    test_results: list[Any] | None = None,
) -> str:
    """Generate an automatic business-language summary of a dataset.

    Parameters
    ----------
    df:
        Historical DataFrame sorted by date.
    date_col:
        Date column.
    target_col:
        Target metric column.
    forecast_result:
        Optional ForecastResult to include forecast narrative.
    test_results:
        Optional list of TestResult objects to include test findings.

    Returns
    -------
    str
        Multi-paragraph business summary text.
    """
    df = df.sort_values(date_col).dropna(subset=[target_col])
    vals = pd.to_numeric(df[target_col], errors="coerce").dropna()

    if vals.empty:
        return "Insufficient data for summary generation."

    paragraphs = []

    # 1. Overall trend
    first_val = float(vals.iloc[0])
    last_val = float(vals.iloc[-1])
    mean_val = float(vals.mean())
    std_val = float(vals.std())
    pct_chg = (last_val - first_val) / abs(first_val) * 100 if first_val != 0 else 0.0
    direction = "increased" if pct_chg > 0 else "decreased"

    paragraphs.append(
        f"**Overall Trend:** {target_col} has {direction} by {abs(pct_chg):.1f}% "
        f"over the observed period (from {first_val:,.2f} to {last_val:,.2f}). "
        f"The mean value was {mean_val:,.2f} with a standard deviation of {std_val:,.2f}."
    )

    # 2. Recent momentum
    if len(vals) >= 3:
        recent = vals.tail(3)
        recent_chg = (float(recent.iloc[-1]) - float(recent.iloc[0])) / abs(float(recent.iloc[0])) * 100 if float(recent.iloc[0]) != 0 else 0.0
        momentum = "accelerating upward" if recent_chg > 2 else "decelerating" if recent_chg < -2 else "relatively stable"
        paragraphs.append(
            f"**Recent Momentum:** Over the last 3 periods, {target_col} has been "
            f"{momentum} ({recent_chg:+.1f}% change)."
        )

    # 3. Volatility
    cv = std_val / abs(mean_val) * 100 if mean_val != 0 else 0.0
    volatility = "low" if cv < 10 else "moderate" if cv < 25 else "high"
    paragraphs.append(
        f"**Volatility:** The coefficient of variation is {cv:.1f}%, "
        f"indicating {volatility} relative volatility."
    )

    # 4. Forecast narrative
    if forecast_result is not None:
        try:
            fc_df = forecast_result.forecast_df
            fut = fc_df[fc_df["actual"].isna() & fc_df["forecast"].notna()]
            if not fut.empty:
                last_forecast = float(fut["forecast"].iloc[-1])
                fc_pct = (last_forecast - last_val) / abs(last_val) * 100 if last_val != 0 else 0.0
                fc_dir = "grow" if fc_pct > 0 else "decline"
                paragraphs.append(
                    f"**Forecast ({forecast_result.model_name}):** The model projects {target_col} "
                    f"to {fc_dir} by {abs(fc_pct):.1f}% to {last_forecast:,.2f} by the end of the forecast horizon. "
                    f"Backtest metrics: MAE={forecast_result.metrics.get('MAE', 'N/A')}, "
                    f"MAPE={forecast_result.metrics.get('MAPE', 'N/A')}%."
                )
        except Exception:
            pass

    # 5. Test findings
    if test_results:
        sig_tests = [t for t in test_results if getattr(t, "significant", False)]
        if sig_tests:
            test_names = ", ".join(t.name for t in sig_tests)
            paragraphs.append(
                f"**Statistical Findings:** The following tests returned significant results "
                f"(p < α): {test_names}. Review the Tests section for full interpretations."
            )
        else:
            paragraphs.append(
                "**Statistical Findings:** No statistically significant differences "
                "were detected in the tests run."
            )

    # 6. Caveats
    n_missing = int(pd.to_numeric(df[target_col], errors="coerce").isna().sum())
    caveats = []
    if n_missing > 0:
        caveats.append(f"{n_missing} missing values in {target_col} were excluded from analysis")
    if len(df) < 24:
        caveats.append("fewer than 24 data points — forecasts may be unreliable")
    if caveats:
        paragraphs.append("**Caveats & Risks:** " + "; ".join(caveats).capitalize() + ".")

    return "\n\n".join(paragraphs)
