"""
core/report_pdf.py – PDF generation backend using reportlab.

Replaces weasyprint (which requires system libs) with pure-Python reportlab.
Public API: generate_pdf_report(df, path) and generate_pdf_bytes(html_content).
"""
from __future__ import annotations

import io
import re
from datetime import datetime
from typing import Any

import pandas as pd


def generate_pdf_report(df: pd.DataFrame, path: str, title: str = "KIBAD Report") -> str:
    """Generate a PDF report from a DataFrame and save to *path*.

    Parameters
    ----------
    df : pd.DataFrame
        Data to include in the report.
    path : str
        Output file path.
    title : str
        Report title.

    Returns
    -------
    str
        The output file path.
    """
    pdf_bytes = _build_pdf(df, title)
    with open(path, "wb") as f:
        f.write(pdf_bytes)
    return path


def generate_pdf_bytes(html_content: str = "", df: pd.DataFrame | None = None,
                       title: str = "KIBAD Report") -> bytes:
    """Generate PDF bytes from HTML content or DataFrame.

    Parameters
    ----------
    html_content : str
        HTML string (simplified text extraction for PDF).
    df : pd.DataFrame, optional
        DataFrame to include as table.
    title : str
        Report title.

    Returns
    -------
    bytes
        PDF file content.
    """
    if df is not None:
        return _build_pdf(df, title)
    return _build_pdf_from_html(html_content, title)


def _build_pdf(df: pd.DataFrame, title: str) -> bytes:
    """Build a PDF with a table from a DataFrame using reportlab."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak,
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=landscape(A4),
                            leftMargin=15*mm, rightMargin=15*mm,
                            topMargin=15*mm, bottomMargin=15*mm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "KibadTitle", parent=styles["Title"],
        fontSize=18, textColor=colors.HexColor("#2c3e50"),
        spaceAfter=12,
    )
    subtitle_style = ParagraphStyle(
        "KibadSubtitle", parent=styles["Normal"],
        fontSize=9, textColor=colors.HexColor("#888888"),
        spaceAfter=20,
    )
    cell_style = ParagraphStyle(
        "CellStyle", parent=styles["Normal"],
        fontSize=7, leading=9,
    )

    elements = []

    # Title
    elements.append(Paragraph(title, title_style))
    elements.append(Paragraph(
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} | "
        f"Rows: {len(df):,} | Columns: {df.shape[1]}",
        subtitle_style,
    ))

    # Table
    max_rows = min(len(df), 200)
    max_cols = min(df.shape[1], 20)
    display_df = df.head(max_rows).iloc[:, :max_cols]

    header = [str(c)[:30] for c in display_df.columns]
    data = [header]
    for _, row in display_df.iterrows():
        data.append([str(v)[:40] for v in row.values])

    col_widths = [max(60, min(120, len(str(c)) * 8)) for c in header]
    total_w = sum(col_widths)
    page_w = landscape(A4)[0] - 30*mm
    if total_w > page_w:
        scale = page_w / total_w
        col_widths = [w * scale for w in col_widths]

    table = Table(data, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#3498db")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 7),
        ("FONTSIZE", (0, 1), (-1, -1), 6.5),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#dddddd")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8f9fa")]),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(table)

    if len(df) > max_rows:
        elements.append(Spacer(1, 10))
        elements.append(Paragraph(
            f"Showing first {max_rows} of {len(df):,} rows.",
            subtitle_style,
        ))

    # Footer
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        f"Generated by KIBAD Analytics Studio | {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        subtitle_style,
    ))

    doc.build(elements)
    return buf.getvalue()


def _build_pdf_from_html(html_content: str, title: str) -> bytes:
    """Build a PDF from HTML content (simplified text extraction)."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=20*mm, rightMargin=20*mm,
                            topMargin=20*mm, bottomMargin=20*mm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "KibadTitle", parent=styles["Title"],
        fontSize=18, textColor=colors.HexColor("#2c3e50"),
        spaceAfter=12,
    )
    body_style = ParagraphStyle(
        "KibadBody", parent=styles["Normal"],
        fontSize=10, leading=14,
        textColor=colors.HexColor("#333333"),
        spaceAfter=8,
    )
    heading_style = ParagraphStyle(
        "KibadH2", parent=styles["Heading2"],
        fontSize=14, textColor=colors.HexColor("#34495e"),
        spaceBefore=16, spaceAfter=8,
    )

    elements = [Paragraph(title, title_style)]

    # Simple HTML → text extraction
    text = re.sub(r'<style[^>]*>.*?</style>', '', html_content, flags=re.DOTALL)
    text = re.sub(r'<script[^>]*>.*?</script>', '', text, flags=re.DOTALL)

    # Extract sections
    sections = re.split(r'<h[12][^>]*>(.*?)</h[12]>', text, flags=re.DOTALL)

    for i, section in enumerate(sections):
        clean = re.sub(r'<[^>]+>', ' ', section).strip()
        clean = re.sub(r'\s+', ' ', clean).strip()
        if not clean:
            continue

        if i % 2 == 1:  # heading
            elements.append(Paragraph(clean[:200], heading_style))
        else:  # body
            paragraphs = clean.split('. ')
            for p in paragraphs:
                p = p.strip()
                if p:
                    try:
                        elements.append(Paragraph(p + '.', body_style))
                    except Exception:
                        pass

    elements.append(Spacer(1, 30))
    elements.append(Paragraph(
        f"Generated by KIBAD | {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        ParagraphStyle("Footer", parent=styles["Normal"],
                       fontSize=8, textColor=colors.HexColor("#aaaaaa")),
    ))

    doc.build(elements)
    return buf.getvalue()
